fix: fixed warning
Yulatun/sandbox-exadel-2022 pull request #82
Opened 2022-08-02 12:22 UTC by HarryPotter-4000

### Description

fixed warning in NavBar Breadcrumb 

### Type of change

- [ ] Feature (introduces new functionality)
- [x] Bugfix
- [ ] Configuration
- [ ] Refactoring (doesn't change functionality, only the code)
- [ ] Style changes (doesn't affect functionality, only the look of the components)

### PR Checklist

- [x] Synced up with latest from the main branch/Code is linted
- [x] Description of the changes has been added (Screenshots/Video)
- [x] Chakra components/constants/hooks have been used wherever possible

> If not explain here

- [x] Commit messages follow [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#summary)
- [x] Console has been checked for warnings

#### Screenshots/Video before change

<img width="1440" alt="warning" src="https://user-images.githubusercontent.com/80061297/182373171-7126d53d-c125-4a3c-a31f-98f5273f7278.png">

2022-08-02 15:08 UTC, Yulatun submitted a review, later dismissed

2022-08-02 15:27 UTC, kalashnikau approved these changes

2022-08-02 21:03 UTC, kalashnikau approved these changes

2022-08-03 12:22 UTC, Yulatun approved these changes

2022-08-03 12:54 UTC, lazzzaroni commented
Sorry for late review, but I have some things to add)

2022-08-03 12:57 UTC, lazzzaroni commented
In src/components/Layout.jsx wrap <Outlet /> into <Container />, like here on screenshot. It helps us keep content in fixed box, if I may say that.
We discuss that moment on daily meeting 🙂

![image](https://user-images.githubusercontent.com/68731150/182613294-57ac38ab-8514-4b1c-ad36-90f0114b45a0.png)

2022-08-03 13:00 UTC, lazzzaroni requested changes

2022-08-03 13:00 UTC, lazzzaroni commented on src/components/Header/Navbar.jsx
> +        <BreadcrumbLink as={Link} to="/incomes">
```suggestion
        <BreadcrumbLink as={Link} to="/incomes" textUnderlineOffset="4px">
```

I think it was missed somehow)

2022-08-03 14:43 UTC, itsnotpolza approved these changes

2022-08-03 15:59 UTC, merged